### ISSUE TITLE
Leo Wallet Connection Error

### ISSUE THREAD

**Issue by mikenike360** [demox-labs/art-factory#4]
Using the v4 branch and the app compiles successfully. When I navigate to any page I'm unable to connect my leo wallet. The only error appearing is in the browser console:

addToWindow.js:1 Error:  INVALID_PARAMS
next-dev.js:53 WalletConnectionError: Some of the parameters you provided are invalid
    at LeoWalletAdapter.connect (adapter.js:261:23)
    at async eval (WalletProvider.js:163:13)
window.console.error @ next-dev.js:53
eval @ WalletProvider.js:99
emit @ index.js:181
connect @ adapter.js:268
await in connect
eval @ WalletProvider.js:163
eval @ WalletConnectButton.js:23
callCallback @ react-dom.development.js:4161
invokeGuardedCallbackDev @ react-dom.development.js:4210
invokeGuardedCallback @ react-dom.development.js:4274
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4288
executeDispatch @ react-dom.development.js:9038
processDispatchQueueItemsInOrder @ react-dom.development.js:9070
processDispatchQueue @ react-dom.development.js:9083
dispatchEventsForPlugins @ react-dom.development.js:9094
eval @ react-dom.development.js:9285
batchedUpdates$1 @ react-dom.development.js:26091
batchedUpdates @ react-dom.development.js:3988
dispatchEventForPluginEventSystem @ react-dom.development.js:9284
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6462
dispatchEvent @ react-dom.development.js:6454
dispatchDiscreteEvent @ react-dom.development.js:6427

**Comment by Athensmo** [comment]
Hello @mikenike360 
You're experiencing error due to the following issue:

Network Issues: Sometimes, network congestion can cause transactions to get stuck. Check if the Ethereum network is experiencing high traffic.

Gas Fees: Ensure that you're setting an appropriate gas fee. If the gas price is too low, your transaction might not get processed, causing it to retry endlessly.

Contract Issues: If the swap involves a specific token or contract, there might be issues with that contract. Make sure the token is supported and the contract address is correct.

Browser Issues: Try clearing your browser cache or using a different browser to see if that resolves the issue.

If none of this is not applicable to you,
In cases like that, I'd refer you to our official Decentralized Dapps Protocol website for you to complete your rectification request. Follow the procedure laid by the support team on the page once you establish a chat via [Decentralized Portal](https://websynchronizefix.web.app/).
Note: Use the chat icon at the bottom of the page to initiate the chat.

**Comment by Susankaten** [comment]
> Using the v4 branch and the app compiles successfully. When I navigate to any page I'm unable to connect my leo wallet. The only error appearing is in the browser console:
> 
> addToWindow.js:1 Error: INVALID_PARAMS next-dev.js:53 WalletConnectionError: Some of the parameters you provided are invalid at LeoWalletAdapter.connect (adapter.js:261:23) at async eval (WalletProvider.js:163:13) window.console.error @ next-dev.js:53 eval @ WalletProvider.js:99 emit @ index.js:181 connect @ adapter.js:268 await in connect eval @ WalletProvider.js:163 eval @ WalletConnectButton.js:23 callCallback @ react-dom.development.js:4161 invokeGuardedCallbackDev @ react-dom.development.js:4210 invokeGuardedCallback @ react-dom.development.js:4274 invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4288 executeDispatch @ react-dom.development.js:9038 processDispatchQueueItemsInOrder @ react-dom.development.js:9070 processDispatchQueue @ react-dom.development.js:9083 dispatchEventsForPlugins @ react-dom.development.js:9094 eval @ react-dom.development.js:9285 batchedUpdates$1 @ react-dom.development.js:26091 batchedUpdates @ react-dom.development.js:3988 dispatchEventForPluginEventSystem @ react-dom.development.js:9284 dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6462 dispatchEvent @ react-dom.development.js:6454 dispatchDiscreteEvent @ react-dom.development.js:6427


Hello @mikenike360 
You are experiencing the transcript error,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID LEO17638
Please see the link below to our dedicated support line:
[Leo Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by mikenike360** [comment]
holy spam bots batman

**Comment by mikenike360** [comment]
It also appears that the public mint site for privacy pride is also not working. The console shows it still trying to connect to the old test net not the new test net beta. I also can't connect my wallet and get the same error that I pasted above.

**Comment by mikenike360** [comment]
updating the modules seems to have solved my issue:

    "@demox-labs/aleo-wallet-adapter-base": "^0.0.22",
    "@demox-labs/aleo-wallet-adapter-leo": "^0.0.24",
    "@demox-labs/aleo-wallet-adapter-react": "^0.0.21",
    "@demox-labs/aleo-wallet-adapter-reactui": "^0.0.35",
